name: project_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - attrs
  - autopep8
  - contourpy
  - matplotlib
  - numpy
  - Pillow
  - pre-commit
  - pytest
  - pytest-cov
  - python-dateutil
  - ruff
  - scipy
  - six
  - sympy
