name: project_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - attrs==22.2.0
  - autopep8==2.0.1
  - contourpy==1.0.7
  - coverage==7.0.5
  - cycler==0.11.0
  - exceptiongroup==1.1.0
  - flake8==6.0.0
  - fonttools==4.38.0
  - iniconfig==2.0.0
  - kiwisolver==1.4.4
  - matplotlib==3.6.3
  - mccabe==0.7.0
  - mpmath==1.2.1
  - numpy==1.24.1
  - packaging==23.0
  - Pillow==9.4.0
  - pluggy==1.0.0
  - pycodestyle==2.10.0
  - pyflakes==3.0.1
  - pyparsing==3.0.9
  - pytest==7.2.0
  - pytest-cov==4.0.0
  - python-dateutil==2.8.2
  - scipy==1.10.0
  - six==1.16.0
  - sympy==1.11.1
  - tomli==2.0.1
