name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3
      - name: Run actions/setup-python@v4
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run actions/cache@v3
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ matrix.python-version }}-dependencies-${{ hashFiles('requirements.txt') }}
      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - name: Lint Code with Flake8
        run: |
          source venv/bin/activate
          flake8 .
      - name: Run Tests with Coverage
        run: |
          source venv/bin/activate
          pytest \
          --cov=$(find . -name "*.py" ! -path "./venv/*")
